In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [3]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [4]:
y

array([ 5, 20, 14, 32, 22, 38])

In [5]:
model = LinearRegression()

In [6]:
model.fit(x, y)

LinearRegression()

In [9]:
model = LinearRegression().fit(x, y)


In [10]:
r_sq = model.score(x, y)
>>> print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


In [11]:
print(f"intercept: {model.intercept_}")

intercept: 5.633333333333329


In [12]:
print(f"slope: {model.coef_}")

slope: [0.54]


In [13]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")

intercept: [5.63333333]


In [14]:
print(f"slope: {new_model.coef_}")

slope: [[0.54]]


In [15]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [16]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [17]:
x_new = np.arange(5).reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [18]:
y_new = model.predict(x_new)
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_csv('Salary_Data.csv')


In [21]:
df.sample(10)

YearsExperience  Salary
27              9.6  112635
21              7.1   98273
1               1.3   46205
19              6.0   93940
0               1.1   39343
15              4.9   67938
14              4.5   61111
24              8.7  109431
4               2.2   39891
9               3.7   57189

In [22]:
df.shape

(30, 2)

In [23]:
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 612.0 bytes


In [25]:
cn = df.corr()
cn

YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [26]:
X = df.drop('Salary',axis=1)
y = df['Salary']

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=11,test_size=20)

In [29]:
X_train

YearsExperience
18              5.9
7               3.2
1               1.3
12              4.0
13              4.1
23              8.2
17              5.3
27              9.6
16              5.1
25              9.0

In [30]:
X_test

YearsExperience
15              4.9
8               3.2
6               3.0
26              9.5
3               2.0
11              4.0
14              4.5
21              7.1
9               3.7
5               2.9
10              3.9
22              7.9
2               1.5
4               2.2
20              6.8
29             10.5
19              6.0
0               1.1
28             10.3
24              8.7

In [31]:
y_train

18     81363
7      54445
1      46205
12     56957
13     57081
23    113812
17     83088
27    112635
16     66029
25    105582
Name: Salary, dtype: int64

In [32]:
y_test

15     67938
8      64445
6      60150
26    116969
3      43525
11     55794
14     61111
21     98273
9      57189
5      56642
10     63218
22    101302
2      37731
4      39891
20     91738
29    121872
19     93940
0      39343
28    122391
24    109431
Name: Salary, dtype: int64

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
lr = LinearRegression()

In [35]:
lr.fit(X_train,y_train)

LinearRegression()

In [36]:
lr.intercept_


26288.653077537972

In [37]:
lr.coef_

array([9233.58113509])

In [38]:
y_pred = lr.predict(X_test)

In [39]:
y_pred

array([ 71533.20063949,  55836.11270983,  53989.39648281, 114007.67386091,
        44755.81534772,  63222.97761791,  67839.76818545,  91847.07913669,
        60452.90327738,  53066.0383693 ,  62299.6195044 ,  99233.94404476,
        40139.02478018,  46602.53157474,  89077.00479616, 123241.254996  ,
        81690.13988809,  36445.59232614, 121394.53876898, 106620.80895284])

In [40]:
y_test

15     67938
8      64445
6      60150
26    116969
3      43525
11     55794
14     61111
21     98273
9      57189
5      56642
10     63218
22    101302
2      37731
4      39891
20     91738
29    121872
19     93940
0      39343
28    122391
24    109431
Name: Salary, dtype: int64

In [41]:
from sklearn import metrics

In [42]:
lr.score(X_test,y_test)

0.9664565446811775